allowBuilds:
  '@parcel/watcher': true
  bcrypt: true
  esbuild: true
  protobufjs: true
  sharp: true

overrides:
  'minimatch@<3.0.5': '3.1.2'
  'ajv@<6.12.3': '6.12.6'
  'fast-xml-parser@<4.4.1': '4.5.1'
  'tar@<6.2.1': '6.2.1'
  'diff@<5.2.0': '5.2.0'
  'multer@<1.4.5-lts.2': '1.4.5-lts.2'
  'cookie@<0.7.0': '0.7.2'
